routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CheckoutController;
use App\Http\Controllers\Admin\FeatureController;
use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SellerController;
use App\Http\Controllers\Admin\SubController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\User\CartController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\WhislistController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('user')
    ->name('user.')
    ->group(function () {
        Route::middleware(['guest:web', 'PreventBackHistory'])->group(
            function () {
                Route::view('/login', 'dashboard.user.login')->name('login');
                Route::view('/register', 'dashboard.user.register')->name(
                    'register'
                );
                Route::post('/create', [UserController::class, 'create'])->name(
                    'create'
                );
                Route::post('/check', [UserController::class, 'check'])->name(
                    'check'
                );
            }
        );

        Route::middleware(['auth:web', 'PreventBackHistory'])->group(
            function () {
                Route::get('/home', [UserController::class, 'home'])->name(
                    'home'
                );
                Route::post('/logout', [UserController::class, 'logout'])->name(
                    'logout'
                );
                Route::get('view_category/{slug}', [
                    UserController::class,
                    'view_category',
                ]);
                Route::get('cat/{subcategory}/{category}', [
                    UserController::class,
                    'viewcategory',
                ]);
                Route::get('view_subcategory/{categories}/{subcategory}', [
                    UserController::class,
                    'view_subcategory',
                ]);
                Route::get('/product/{subcategory_slug}/{product_slug}', [
                    UserController::class,
                    'display_product',
                ]);
                Route::get('product_details/{slug}', [UserController::class, 'detailsviews']);
                Route::post('add_to_cart', [
                    CartController::class,
                    'addProduct',
                ]);
                Route::get('view_cart', [CartController::class, 'index']);
                Route::post('delete_cart_item', [
                    CartController::class,
                    'destroy',
                ]);
                Route::post('update_cart', [CartController::class, 'update']);
                Route::get('/checkout', [
                    CheckoutController::class,
                    'index',
                ])->name('checkout');
                Route::post('/placeOrder', [
                    CheckoutController::class,
                    'placeOrder',
                ])->name('placeOrder');
                Route::get('/user_details', [
                    UserController::class,
                    'userindex',
                ])->name('user_details');
                Route::get('/categories', [
                    UserController::class,
                    'category',
                ])->name('categories');
                Route::get('/add_details', [
                    UserController::class,
                    'add_details',
                ])->name('add_details');
                Route::post('/create_userdetails', [
                    UserController::class,
                    'add_user_details',
                ])->name('create_userdetails');
                Route::get('/details_product/{slug}', [
                    ProductController::class,
                    'detail',
                ]);
                Route::get('/viewdetails/{slug}', [UserController::class, 'details']);
                Route::get('/viewOrders', [
                    OrderController::class,
                    'viewOrders',
                ])->name('viewOrders');
                Route::get('/whislist', [
                    WhislistController::class,
                    'index',
                ])->name('whislist');
                Route::post('/add_to_whislist', [
                    WhislistController::class,
                    'add_to_whislist',
                ])->name('add_to_whislist');

                Route::post('delete_wishlist', [
                    WhislistController::class,
                    'delete_wishlist',
                ]);
                Route::get('load_cart_data', [
                    CartController::class,
                    'cartcount',
                ]);
                Route::get('load-wishlist-count', [
                    WhislistController::class,
                    'whislist_count',
                ]);
                Route::get('viewProduct', [
                    ProductController::class,
                    'viewProduct',
                ])->name('viewProduct');
                Route::post('proceed-to-pay', [
                    PaymentController::class,
                    'razorpaycheck',
                ]);
            }
        );
    });
Route::prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::middleware(['guest:admin', 'PreventBackHistory'])->group(
            function () {
                Route::view('/login', 'dashboard.admin.login')->name('login');
                Route::post('/check', [AdminController::class, 'check'])->name(
                    'check'
                );
            }
        );

        Route::middleware(['auth:admin', 'PreventBackHistory'])->group(
            function () {
                Route::view('/home', 'dashboard.admin.home')->name('home');
                Route::get('/category', [
                    CategoryController::class,
                    'index',
                ])->name('category');
                Route::get('/add_category', [
                    CategoryController::class,
                    'viewcat',
                ])->name('add_category');
                Route::post('/logout', [
                    AdminController::class,
                    'logout',
                ])->name('logout');
                Route::post('/create_category', [
                    CategoryController::class,
                    'create_category',
                ])->name('create_category');
                // Route::view('/product','dashboard.admin.product.index')->name('product');
                Route::get('/product', [
                    ProductController::class,
                    'index',
                ])->name('product');
                Route::get('/add_product', [
                    ProductController::class,
                    'add_product',
                ])->name('add_product');
                Route::post('/create_product', [
                    ProductController::class,
                    'create_product',
                ])->name('create_product');
                Route::get('/seller', [SellerController::class, 'index'])->name(
                    'seller'
                );
                Route::get('/add_seller', [
                    SellerController::class,
                    'create',
                ])->name('add_seller');
                Route::post('/create_seller', [
                    SellerController::class,
                    'store',
                ])->name('create_seller');
                Route::get('/features', [
                    FeatureController::class,
                    'index',
                ])->name('features');
                Route::get('add_feature/{id}', [
                    FeatureController::class,
                    'add_feature',
                ])->name('add_feature');
                Route::post('/create_feature', [
                    FeatureController::class,
                    'store',
                ])->name('create_feature');
                Route::get('/trending', [
                    CategoryController::class,
                    'trending',
                ])->name('trending');
                Route::get('/edit_category/{id}', [
                    CategoryController::class,
                    'edit',
                ])->name('edit_category');
                Route::put('/update_category/{id}', [
                    CategoryController::class,
                    'update',
                ]);
                Route::delete('delete_category/{id}', [
                    CategoryController::class,
                    'destroy',
                ]);
                Route::get('/edit_product/{id}', [
                    ProductController::class,
                    'edit',
                ])->name('edit_product');
                Route::put('/update_product/{id}', [
                    ProductController::class,
                    'update',
                ]);
                Route::delete('delete_product/{id}', [
                    ProductController::class,
                    'destroy',
                ]);
                Route::get('/view_products/{slug}', [
                    UserController::class,

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function cart()
    {
        return $this->hasMany('App\Models\Cart');
    }
}

app/Http/Controllers/User/CartController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\Category;
use App\Models\Groups;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PHPUnit\TextUI\XmlConfiguration\Group;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $cartItem= Cart::where('user_id',Auth::guard('web')->user()->id)->get();
        $groups=Groups::all();
        return view('dashboard.user.cart.index',compact('cartItem','groups'));
    }
function addProduct(Request $request){
    $product_id = $request->input('product_id');
    $product_quantity = $request->input('product_quantity');

    $product_check = Product::where('id',$product_id)->first();
    if($product_check){
        if(Cart::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->exists()){
            return response()->json(['status'=> $product_check->name." Already added to cart"]);
        }
        else{
            $cartItem = new Cart();
            $cartItem->product_id= $product_id;

            $cartItem->user_id = Auth::guard('web')->user()->id;
            $cartItem->product_quantity= $product_quantity;
            $cartItem->save();
            return response()->json(['status'=> $product_check->product_name." Added to cart"]);
            // return response()->json(['status'=>200,'message'=> 'Added to cart']);
        }

    }
}
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)

    {
      $product_id= $request->input('product_id');
      $product_quantity= $request->input('product_quantity');
      if(Cart::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->first()){
        $cartItem= Cart::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->first();
        $cartItem->product_quantity = $product_quantity;
        $cartItem->update();

        return response()->json(['status'=>" Item Updated Succesfully"]);
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $product_id= $request->input('product_id');
        if(Cart::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->first()){
            $cartItem= Cart::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->first();
            $cartItem->delete();
            return response()->json(['status'=>" Item Deleted Succesfully"]);
        }


    }
    function cartcount(){
        $cartcount = Cart::where('user_id',Auth::guard('web')->user()->id)->count();
        return response()->json(['count'=>$cartcount]);
    }
}

app/Http/Controllers/User/OrderController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Groups;
use App\Models\Order;
use App\Models\OrderItems;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
class OrderController extends Controller
{
  function viewOrders(){
    $groups=Groups::all();
      $order  = Order::where('user_id',  Auth::guard('web')->user()->id)->get();
      // $orderItems  = OrderItems::all();
      return view('dashboard.user.order.index',compact('groups','order',));
  }
}

app/Http/Controllers/User/WhislistController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\Whishlist;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;

class WhislistController extends Controller
{
    function index(){
        $category = Category::all();
        $whishlist = Whishlist::where('user_id',Auth::guard('web')->user()->id)->get();
        return view('dashboard.user.whishlist.index',compact('category','whishlist'));
    }
    function add_to_whislist(Request $request){
        $product_id = $request->input('product_id');
        $product_check = Product::where('id',$product_id)->first();
        if(Whishlist::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->exists()){
            return response()->json(['status'=> $product_check->name." Already added to cart"]);
        }
        elseif(Product::find($product_id)){
            $whish = new Whishlist();
            $whish->product_id = $product_id;
            $whish->user_id= Auth::guard('web')->user()->id;
            $whish->save();
            return response()->json(['status'=>"Product added to whishlist"]);
        }
        else{
            return response()->json(['status'=>"Product Doesnot exists"]);
        }
    }
    function delete_wishlist(Request $request){
        $product_id= $request->input('product_id');
        if(Whishlist::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->first()){
            $whishlist= Whishlist::where('product_id',$product_id)->where('user_id',Auth::guard('web')->user()->id)->first();
            $whishlist->delete();
            return response()->json(['status'=>" Item Deleted Succesfully"]);
        }

    }
    function whislist_count(){
        $whislist_count = Whishlist::where('user_id',Auth::guard('web')->user()->id)->count();
        return response()->json(['success'=>$whislist_count]);
        return Response::make("status", 204);
    }
}

resources/views/dashboard/user/user_details/add_details.blade.php
@extends('dashboard.user.layouts.master')

@section('content')
    <section class="checkout-wrapper section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="checkout-steps-form-style-1">
                        <ul id="accordionExample">
                            <li>
                                <h6 class="title" data-bs-toggle="collapse" data-bs-target="#collapseThree"
                                    aria-expanded="true" aria-controls="collapseThree">Your Personal Details </h6>
                                <section class="checkout-steps-form-content collapse show" id="collapseThree"
                                    aria-labelledby="headingThree" data-bs-parent="#accordionExample">

                                    <form action="{{ route('user.create_userdetails') }}" method="post" autocomplete="off"
                                        class="forms-sample" enctype="multipart/form-data">
                                        @csrf
                                        <div class="row">
                                            @foreach ($user as $user)
                                                <input type="hidden" value="{{ $user->id }}" name="user_id">
                                            @endforeach

                                                <div class="col-md-6">

                                                    <div class="single-form form-default form-group row">
                                                        <label>First Name</label>
                                                        <div class="form-input form">
                                                            <input type="text" placeholder="Enter your first name"
                                                                name="first_name">
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-md-6">

                                                    <div class="single-form form-default form-group row">
                                                        <label>Last Name</label>
                                                        <div class="form-input form">
                                                            <input type="text" placeholder="Enter your last name"
                                                                name="last_name" >
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">

                                                    <div class="single-form form-default form-group row">
                                                        <label>Address</label>
                                                        <div class="form-input form">
                                                            <input type="text" placeholder="Enter your address"
                                                                name="address" >
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="single-form form-default form-group row">
                                                        <label>Country</label>
                                                        <div class="select-items">
                                                            <select class="form-control" name="country"
                                                              >
                                                                <option value="0">Choose Country</option>
                                                                <option value="Nepal">Nepal</option>
                                                                <option value="India">India</option>
                                                                <option value="China">China</option>
                                                                <option value="Bangladesh">Bangladesh</option>
                                                                <option value="Bhutan">Bhutan</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">

                                                    <div class="single-form form-default form-group row">
                                                        <label>Phone Number</label>
                                                        <div class="form-input form">
                                                            <input type="text" placeholder="Phone Number" name="contact"
                                                               >
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="single-form form-default form-group row">
                                                        <label>City</label>
                                                        <div class="form-input form">
                                                            <input type="text" placeholder="City" name="city"
                                                              >
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="single-form form-default form-group row">
                                                        <label>Post Code</label>
                                                        <div class="form-input form">
                                                            <input type="text" placeholder="Post Code" name="postal_code"
                                                               >
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="single-form form-default">
                                                        <label>Profile Image</label>
                                                        <div>
                                                            <input type="file" name="profile_image"
                                                              >
                                                        </div>
                                                    </div>
                                                </div>

                                            <div class="col-md-12">
                                                <div class="single-form button">
                                                    <button type="submit" class="btn btn-warning me-2">Update
                                                        Details</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>

                                </section>
                            </li>
                        </ul>
                    </div>
                </div>
    </section>
@endsection

resources/views/dashboard/user/user_details/index.blade.php
@extends('dashboard.user.layouts.master')

@section('content')
    <!--====== Start Profile One ======-->
    <br>
    <div class="profile">


        <div class="container">
            <div class="profile-content">
                <div class="profile-card">
                    <div class="profile-card-wrapper">
                        <div class="card-header bg_cover" style="
                                background-image: url(https://cdn.ayroui.com/1.0/images/profile/card-bg.jpg);
                                "></div>
                        <!-- card-header -->
                        <div class="card-profile">
                            <img src="https://cdn.ayroui.com/1.0/images/profile/profile.jpg" alt="Profile" />

                        </div>
                        <!-- card-profile -->
                        <div class="card-content text-center rounded-buttons">
                            <h6 class="card-title">
                                {{ Auth::guard('web')->user()->name }}</h6>
                            <h6>
                                {{ Auth::guard('web')->user()->email }}
                            </h6>

                        </div>
                        <div class="card-body">
                            <section class="profile-section ">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="user-title">
                                                <h4>Profile Details <a href="{{route('user.add_details')}}"
                                                        class="btn btn-outline-primary float-end">Edit</a> </h4>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </section>

                        </div>
                        <!-- profile-card -->
                    </div>
                    <!-- profile-card -->
                </div>


            </div>
        </div>
        <!--====== End Profile One ======-->

        <section class="user-grids">
            <div class="container">
                <div class="row">

                    <div class="col-lg-9 col-12">
                        <div class="product-grids-head">
                            <div class="product-grid-topbar">
                                <div class="row align-items-center">
                                    <div class="col-lg-12 col-md-8 col-12">
                                        <div class="product-sorting">
                                            <label for="sorting">Username:</label>
                                            <label for="sorting">Sanish Maharjan</label>
                                        </div>
                                        <div class="product-sorting">
                                            <label for="sorting"> Email:</label>
                                            <label for="sorting"> doe@email.com</label>
                                        </div>
                                        <div class="product-sorting">
                                            <label for="sorting">Phone:</label>
                                            <label for="sorting">+123 456 789 0234</label>
                                        </div>
                                        <div class="product-sorting">
                                            <label for="sorting">Address:</label>
                                            <label for="sorting">Company Inc., 8901 Marmora Road, Glasgow, D04 89GR.</label>
                                        </div>
                                        <div class="product-sorting">
                                            <label for="sorting">Gender:</label>
                                            <label for="sorting">Male</label>


                                        </div>
                                        <div class="product-sorting">
                                            <label for="sorting">Birthday:</label>
                                            <label for="sorting">
                                                04 January 1992</label>


                                        </div>

                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    @endsection